# Generated by Django 4.1.6 on 2023-04-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
